### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by chronon** [eberfreitas/cakephp-slugomatic#5]
It would be helpful to have a tagged release (for composer). Something like:

```
git tag 1.0
git push --tags
```

**Comment by eberfreitas** [comment]
It is a nice idea, but this is such a simple plugin. Right now I don't see anyway of breaking things. If we start to develop it to cake 3 and have to change a lot of things, maybe it is a good idea to start using versions. For now I guess that using the dev-master is the best way to go. But yeah. I can't see myself rebuilding it for cake 3, so we will see the use of tags and new branches soon.

**Comment by chronon** [comment]
That's fine, though I still don't like to require `dev-master` in a composer.json. Instead of:
```
"eberfreitas/cakephp-slugomatic": "1.0.x"
```
I now have
```
"eberfreitas/cakephp-slugomatic": "dev-master#aa9edd8f0f0c5612b4fbb32a09cf30a7b8ac5136"
```
Since GitHub automagically makes releases from simply pushing a tag, I thought I would suggest it.

**Comment by eberfreitas** [comment]
@chronon It was incredibly easy to do this so I did it. Sorry it took me so long. Here it is:

https://github.com/eberfreitas/cakephp-slugomatic/releases/tag/0.1.0

**Comment by chronon** [comment]
:+1:
